// <auto-generated />
using System;
using CinemaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaApp.Data.Migrations
{
    [DbContext(typeof(CinemaAppDbContext))]
    partial class CinemaAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaApp.Data.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfd11aad-df32-42cf-a5bc-fefa8761cfa8"),
                            Description = "A skilled thief is given a chance at redemption if he can successfully perform an inception on a target's mind.",
                            Director = "Christopher Nolan",
                            Duration = 148,
                            Genre = "Sci-Fi",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0057/3728/3618/files/inception.mpw.123395_9e0000d1-bc7f-400a- b488-15fa9e60a10c_500x749.jpg?v=1708527589",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = new Guid("13d3e604-9d3f-4a65-96ac-b435e376a470"),
                            Description = "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
                            Director = "Francis Ford Coppola",
                            Duration = 175,
                            Genre = "Crime",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/b5282f72126e4919911509e034a61f66_6ce2486d-   e0da-4b7a-9148-722cdde610b8_480x.progressive.jpg?v=1573616025",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = new Guid("68af2aab-4a35-42d6-8a23-bd86834d723e"),
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Director = "Christopher Nolan",
                            Duration = 169,
                            Genre = "Adventure",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/interstellar-139399_480x.progressive.jpg?v=1708527823",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = new Guid("a9c0dfda-a835-41fc-ade9-8d5da156e03e"),
                            Description = "Batman faces the Joker, a criminal mastermind bent on causing chaos in Gotham City.",
                            Director = "Christopher Nolan",
                            Duration = 152,
                            Genre = "Action",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/darkknight.building.24x36_20e90057- f673-4cc3-9ce7-7b0d3eeb7d83_480x.progressive.jpg?v=1707491191",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = new Guid("bb478a09-eeb7-41ee-9441-82c1fd0b6b80"),
                            Description = "The lives of two mob hitmen, a boxer, and others intertwine in a series of unexpected incidents.",
                            Director = "Quentin Tarantino",
                            Duration = 154,
                            Genre = "Crime",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/pulpfiction.2436_480x.progressive.jpg?v=1620048742",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = new Guid("ea4abe16-1b17-4d0a-899f-c4ad56705a5e"),
                            Description = "A computer hacker learns the shocking truth about the reality he lives in and joins a rebellion.",
                            Director = "The Wachowskis",
                            Duration = 136,
                            Genre = "Sci-Fi",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/Matrix.mpw.102176_bb2f6cc5-4a16-4512-881b-  f855ead3c8ec_480x.progressive.jpg?v=1708703624",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = new Guid("e663e4d5-b828-4c21-b73c-034de46428d8"),
                            Description = "A businessman saves the lives of hundreds of Jews during the Holocaust by employing them in his factories.",
                            Director = "Steven Spielberg",
                            Duration = 195,
                            Genre = "Drama",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/9a1f9ea4a27071481cc1263e3ea11f7b_7bdb2deb-dd50-41b5- beab-8fc1cb3c895d_480x.progressive.jpg?v=1573651233",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1993, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id = new Guid("e6316357-ffa9-4584-bb59-179b7f98b92a"),
                            Description = "The story of Forrest Gump, a man with a low IQ, whose kind heart shapes the lives of those around him.",
                            Director = "Robert Zemeckis",
                            Duration = 142,
                            Genre = "Drama",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/forrest-gump---24x36_480x.progressive.jpg?v=1645558337",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = new Guid("89d4998c-461f-4ce2-ae91-fcddc7f4f1e8"),
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of decency.",
                            Director = "Frank Darabont",
                            Duration = 142,
                            Genre = "Drama",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/shawshank_eb84716b-efa9-44dc-a19d-c17924a3f7df_480x.progressive.jpg?    v=1709821984",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1994, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = new Guid("42f05318-ed1a-415c-baac-d78bd71fa774"),
                            Description = "A paraplegic Marine dispatched to the moon Pandora becomes torn between following orders and protecting his home.",
                            Director = "James Cameron",
                            Duration = 162,
                            Genre = "Sci-Fi",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/avatar.adv.24x36_480x.progressive.jpg?v=1707410703",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2009, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = new Guid("bc61e67d-3d38-4d8e-8413-66ad1c9ac320"),
                            Description = "A betrayed Roman general seeks revenge against the corrupt emperor who murdered his family and sent him into     slavery.",
                            Director = "Ridley Scott",
                            Duration = 155,
                            Genre = "Action",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/Gladiator.mpw.102813_480x.progressive.jpg?v=1707500493",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = new Guid("159c21f2-0e63-46f2-967a-bdc1e3720b4c"),
                            Description = "Earth's mightiest heroes must come together to stop a mischievous Loki and his alien army.",
                            Director = "Joss Whedon",
                            Duration = 143,
                            Genre = "Action",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/avengers.24x36_480x.progressive.jpg?v=1707410714",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2012, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Avengers"
                        },
                        new
                        {
                            Id = new Guid("48dfe47e-6f93-4b6e-969f-43d39d81d44c"),
                            Description = "A lion prince flees his kingdom after the death of his father, only to learn the true meaning of responsibility and  bravery.",
                            Director = "Roger Allers, Rob Minkoff",
                            Duration = 88,
                            Genre = "Animation",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/the-lion-king_273b54a5_480x.progressive.jpg?v=1725905168",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1994, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lion King"
                        },
                        new
                        {
                            Id = new Guid("9d2d04a3-cef8-4d46-9fde-b253efc65253"),
                            Description = "During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run  amok.",
                            Director = "Steven Spielberg",
                            Duration = 127,
                            Genre = "Adventure",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/jurassic-park-1_480x.progressive.jpg?v=1708686293",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id = new Guid("b598840f-334b-478d-9afe-23674d2fd5df"),
                            Description = "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the ill-fated R.M.S. Titanic.",
                            Director = "James Cameron",
                            Duration = 195,
                            Genre = "Romance",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/titanic.24x36_480x.progressive.jpg?v=1707410721",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1997, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Titanic"
                        },
                        new
                        {
                            Id = new Guid("c252982a-da71-44c1-84b7-44e1a8375c84"),
                            Description = "A young FBI cadet must confide in an incarcerated cannibal to catch another serial killer.",
                            Director = "Jonathan Demme",
                            Duration = 118,
                            Genre = "Thriller",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/The_Silence_of_the_Lambs_Movie_Poster_480x.progressive.jpg?v=1707410734",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1991, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id = new Guid("c7a04b89-a363-438f-b516-45d8260687c8"),
                            Description = "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper.",
                            Director = "Steven Spielberg",
                            Duration = 169,
                            Genre = "War",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/saving-private-ryan-24x36_480x.progressive.jpg?v=1707410738",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1998, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Saving Private Ryan"
                        },
                        new
                        {
                            Id = new Guid("15c98ef8-3c66-42ef-8eca-76b73d0434fb"),
                            Description = "An insomniac office worker and a soap maker form an underground fight club.",
                            Director = "David Fincher",
                            Duration = 139,
                            Genre = "Drama",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/fightclub.24x36_480x.progressive.jpg?v=1707410744",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1999, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = new Guid("1616d7d0-e9e9-4d01-a323-af6a76b6bb26"),
                            Description = "Two magicians engage in a bitter rivalry with deadly consequences.",
                            Director = "Christopher Nolan",
                            Duration = 130,
                            Genre = "Mystery",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/the-prestige-24x36_480x.progressive.jpg?v=1707410754",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2006, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Prestige"
                        },
                        new
                        {
                            Id = new Guid("1533e58e-6da4-47eb-9013-2bf82ec42351"),
                            Description = "A group of intergalactic criminals must work together to stop a fanatical warrior from taking control of the     universe.",
                            Director = "James Gunn",
                            Duration = 121,
                            Genre = "Action",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/guardiansofthegalaxy.24x36_480x.progressive.jpg?v=1707410763",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2014, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Guardians of the Galaxy"
                        },
                        new
                        {
                            Id = new Guid("7a9f8ec8-63ef-4777-a7e3-236c8443d836"),
                            Description = "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, and others to save the galaxy from the Empire's   world-destroying weapon.",
                            Director = "George Lucas",
                            Duration = 121,
                            Genre = "Sci-Fi",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/starwars-episode-iv_480x.progressive.jpg?v=1707410770",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1977, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: Episode IV - A New Hope"
                        },
                        new
                        {
                            Id = new Guid("dfa76ab8-bc25-488f-810c-5567eae15b63"),
                            Description = "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang.",
                            Director = "Martin Scorsese",
                            Duration = 151,
                            Genre = "Crime",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/thedeparted.24x36_480x.progressive.jpg?v=1707410777",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2006, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Departed"
                        },
                        new
                        {
                            Id = new Guid("34cdc33d-1055-43e3-a1a7-6f9547f28927"),
                            Description = "With the help of a bounty hunter, a freed slave sets out to rescue his wife from a brutal plantation owner.",
                            Director = "Quentin Tarantino",
                            Duration = 165,
                            Genre = "Western",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/djangounchained.24x36_480x.progressive.jpg?v=1707410784",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Django Unchained"
                        },
                        new
                        {
                            Id = new Guid("cd2e4303-c313-4af1-bda1-829f152b2fa1"),
                            Description = "T'Challa returns home to Wakanda to take his throne but faces challenges from a rival claimant.",
                            Director = "Ryan Coogler",
                            Duration = 134,
                            Genre = "Action",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/blackpanther.24x36_480x.progressive.jpg?v=1707410790",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2018, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black Panther"
                        },
                        new
                        {
                            Id = new Guid("c9a04471-ddd6-44cf-a061-76eeb2aa007c"),
                            Description = "A skilled thief is given a chance at redemption if he can successfully perform an inception on a target's mind.",
                            Director = "Christopher Nolan",
                            Duration = 148,
                            Genre = "Sci-Fi",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0057/3728/3618/files/inception.mpw.123395_9e0000d1-bc7f-400a- b488-15fa9e60a10c_500x749.jpg?v=1708527589",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = new Guid("37ab596c-7547-477c-b68a-5948363f14bf"),
                            Description = "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
                            Director = "Francis Ford Coppola",
                            Duration = 175,
                            Genre = "Crime",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/b5282f72126e4919911509e034a61f66_6ce2486d-   e0da-4b7a-9148-722cdde610b8_480x.progressive.jpg?v=1573616025",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = new Guid("415c94e9-fb91-429e-9aef-7356ea45d337"),
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Director = "Christopher Nolan",
                            Duration = 169,
                            Genre = "Adventure",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/interstellar-139399_480x.progressive.jpg?v=1708527823",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = new Guid("b9f610d4-88ab-4371-9f33-bbd1d768146b"),
                            Description = "Batman faces the Joker, a criminal mastermind bent on causing chaos in Gotham City.",
                            Director = "Christopher Nolan",
                            Duration = 152,
                            Genre = "Action",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/darkknight.building.24x36_20e90057- f673-4cc3-9ce7-7b0d3eeb7d83_480x.progressive.jpg?v=1707491191",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = new Guid("13f493c3-790f-4552-8d34-1e7b2a8d2aaf"),
                            Description = "The lives of two mob hitmen, a boxer, and others intertwine in a series of unexpected incidents.",
                            Director = "Quentin Tarantino",
                            Duration = 154,
                            Genre = "Crime",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/pulpfiction.2436_480x.progressive.jpg?v=1620048742",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = new Guid("97409530-7a89-4c7c-bd5e-e85592caa0fd"),
                            Description = "A computer hacker learns the shocking truth about the reality he lives in and joins a rebellion.",
                            Director = "The Wachowskis",
                            Duration = 136,
                            Genre = "Sci-Fi",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/Matrix.mpw.102176_bb2f6cc5-4a16-4512-881b-  f855ead3c8ec_480x.progressive.jpg?v=1708703624",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = new Guid("4cd95d91-6d2b-4a74-b2e2-aec46b028f3f"),
                            Description = "A businessman saves the lives of hundreds of Jews during the Holocaust by employing them in his factories.",
                            Director = "Steven Spielberg",
                            Duration = 195,
                            Genre = "Drama",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/9a1f9ea4a27071481cc1263e3ea11f7b_7bdb2deb-dd50-41b5- beab-8fc1cb3c895d_480x.progressive.jpg?v=1573651233",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1993, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id = new Guid("08916a91-81e7-425a-bf7a-0b984e700e38"),
                            Description = "The story of Forrest Gump, a man with a low IQ, whose kind heart shapes the lives of those around him.",
                            Director = "Robert Zemeckis",
                            Duration = 142,
                            Genre = "Drama",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/forrest-gump---24x36_480x.progressive.jpg?v=1645558337",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = new Guid("fcbce5b4-d65e-45d0-9fb9-072f514e8972"),
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of decency.",
                            Director = "Frank Darabont",
                            Duration = 142,
                            Genre = "Drama",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/shawshank_eb84716b-efa9-44dc-a19d-c17924a3f7df_480x.progressive.jpg?    v=1709821984",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1994, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = new Guid("35e6a5fd-089b-4e63-9515-9d61774902dc"),
                            Description = "A paraplegic Marine dispatched to the moon Pandora becomes torn between following orders and protecting his home.",
                            Director = "James Cameron",
                            Duration = 162,
                            Genre = "Sci-Fi",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/avatar.adv.24x36_480x.progressive.jpg?v=1707410703",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2009, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = new Guid("09f0ddfa-98ff-4ce2-97ec-eabd1e89f6ca"),
                            Description = "A betrayed Roman general seeks revenge against the corrupt emperor who murdered his family and sent him into     slavery.",
                            Director = "Ridley Scott",
                            Duration = 155,
                            Genre = "Action",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/Gladiator.mpw.102813_480x.progressive.jpg?v=1707500493",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = new Guid("ec009376-e3c0-4ddc-9a3c-8ab516d87a71"),
                            Description = "Earth's mightiest heroes must come together to stop a mischievous Loki and his alien army.",
                            Director = "Joss Whedon",
                            Duration = 143,
                            Genre = "Action",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/avengers.24x36_480x.progressive.jpg?v=1707410714",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2012, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Avengers"
                        },
                        new
                        {
                            Id = new Guid("62485b6c-11d3-4b9c-bbef-d51582a07039"),
                            Description = "A lion prince flees his kingdom after the death of his father, only to learn the true meaning of responsibility and  bravery.",
                            Director = "Roger Allers, Rob Minkoff",
                            Duration = 88,
                            Genre = "Animation",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/the-lion-king_273b54a5_480x.progressive.jpg?v=1725905168",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1994, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lion King"
                        },
                        new
                        {
                            Id = new Guid("3d8a1587-ff50-4076-8179-98e71ac0796a"),
                            Description = "During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run  amok.",
                            Director = "Steven Spielberg",
                            Duration = 127,
                            Genre = "Adventure",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/jurassic-park-1_480x.progressive.jpg?v=1708686293",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id = new Guid("21b11216-4b90-465f-a278-5f5a65c61e88"),
                            Description = "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the ill-fated R.M.S. Titanic.",
                            Director = "James Cameron",
                            Duration = 195,
                            Genre = "Romance",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/files/titanic.24x36_480x.progressive.jpg?v=1707410721",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1997, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Titanic"
                        },
                        new
                        {
                            Id = new Guid("09456213-94a2-4a09-9216-86757c792a74"),
                            Description = "A young FBI cadet must confide in an incarcerated cannibal to catch another serial killer.",
                            Director = "Jonathan Demme",
                            Duration = 118,
                            Genre = "Thriller",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/The_Silence_of_the_Lambs_Movie_Poster_480x.progressive.jpg?v=1707410734",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1991, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id = new Guid("4597842b-aeae-4133-89e2-c083917cf8d9"),
                            Description = "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper.",
                            Director = "Steven Spielberg",
                            Duration = 169,
                            Genre = "War",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/saving-private-ryan-24x36_480x.progressive.jpg?v=1707410738",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1998, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Saving Private Ryan"
                        },
                        new
                        {
                            Id = new Guid("1eb2e86c-ba5c-42c4-8b52-c37675463918"),
                            Description = "An insomniac office worker and a soap maker form an underground fight club.",
                            Director = "David Fincher",
                            Duration = 139,
                            Genre = "Drama",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/fightclub.24x36_480x.progressive.jpg?v=1707410744",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1999, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = new Guid("59562e20-dd38-4dd0-833c-4fe11cf29451"),
                            Description = "Two magicians engage in a bitter rivalry with deadly consequences.",
                            Director = "Christopher Nolan",
                            Duration = 130,
                            Genre = "Mystery",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/the-prestige-24x36_480x.progressive.jpg?v=1707410754",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2006, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Prestige"
                        },
                        new
                        {
                            Id = new Guid("8799f03d-c7a2-49f1-bcb3-a4213dd65b07"),
                            Description = "A group of intergalactic criminals must work together to stop a fanatical warrior from taking control of the     universe.",
                            Director = "James Gunn",
                            Duration = 121,
                            Genre = "Action",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/guardiansofthegalaxy.24x36_480x.progressive.jpg?v=1707410763",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2014, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Guardians of the Galaxy"
                        },
                        new
                        {
                            Id = new Guid("1ebd874f-ec2d-42f7-859a-73224c5395e4"),
                            Description = "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, and others to save the galaxy from the Empire's   world-destroying weapon.",
                            Director = "George Lucas",
                            Duration = 121,
                            Genre = "Sci-Fi",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/starwars-episode-iv_480x.progressive.jpg?v=1707410770",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(1977, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: Episode IV - A New Hope"
                        },
                        new
                        {
                            Id = new Guid("cc438584-3c7e-48d4-9dcc-eb13c37220f2"),
                            Description = "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang.",
                            Director = "Martin Scorsese",
                            Duration = 151,
                            Genre = "Crime",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/thedeparted.24x36_480x.progressive.jpg?v=1707410777",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2006, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Departed"
                        },
                        new
                        {
                            Id = new Guid("c9d8efbe-a9b4-4dca-88d5-49efb4e9cc5c"),
                            Description = "With the help of a bounty hunter, a freed slave sets out to rescue his wife from a brutal plantation owner.",
                            Director = "Quentin Tarantino",
                            Duration = 165,
                            Genre = "Western",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/djangounchained.24x36_480x.progressive.jpg?v=1707410784",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Django Unchained"
                        },
                        new
                        {
                            Id = new Guid("db679cf5-844b-4489-b846-8c772ed59d96"),
                            Description = "T'Challa returns home to Wakanda to take his throne but faces challenges from a rival claimant.",
                            Director = "Ryan Coogler",
                            Duration = 134,
                            Genre = "Action",
                            ImageUrl = "https://www.movieposters.com/cdn/shop/products/blackpanther.24x36_480x.progressive.jpg?v=1707410790",
                            IsDeleted = false,
                            ReleaseDate = new DateTime(2018, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black Panther"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
